version: "3.8"

networks:
  default: {}

services:
  nextjs:
    image: node:18
    working_dir: /scripts
    volumes:
      - ./:/scripts
    environment:
      - NODE_LOGGING_LEVEL=debug
    ports:
      - 3000:3000
    entrypoint: [bash, -c, "npm install && npm run build && npm run start"]
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: aSecret
      MYSQL_DATABASE: homestead
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 4s
      retries: 50
